export const playerList = [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Neymar",
    "Kylian Mbappé",
    "Robert Lewandowski",
    "Mohamed Salah",
    "Kevin De Bruyne",
    "Sergio Ramos",
    "Luka Modrić",
    "Harry Kane",
    "Karim Benzema",
    "Erling Haaland",
    "Virgil van Dijk",
    "N'Golo Kanté",
    "Manuel Neuer",
    "Antoine Griezmann",
    "Paulo Dybala",
    "Sergio Agüero",
    "Eden Hazard",
    "Gianluigi Donnarumma",
    "Paul Pogba",
    "Jadon Sancho",
    "Raheem Sterling",
    "Romelu Lukaku",
    "Thiago Silva",
    "Thomas Müller",
    "Alisson Becker",
    "Jan Oblak",
    "Trent Alexander-Arnold",
    "Joshua Kimmich",
    "Jordi Alba",
    "Frenkie de Jong",
    "Marcus Rashford",
    "Kalidou Koulibaly",
    "Zlatan Ibrahimović",
    "David Alaba",
    "Marco Reus",
    "Sadio Mané",
    "Leroy Sané",
    "Marcelo Vieira",
    "Gerard Piqué",
    "David de Gea",
    "Edinson Cavani",
    "Philippe Coutinho",
    "Pierre-Emerick Aubameyang",
    "Ciro Immobile",
    "Angel Di Maria",
    "Hakim Ziyech",
    "Dani Carvajal",
    "Andrew Robertson",
    "Sergio Busquets",
    "Casemiro",
    "Kai Havertz",
    "Timo Werner",
    "Dani Alves",
    "Fabinho",
    "Jordan Henderson",
    "Matthijs de Ligt",
    "Leonardo Bonucci",
    "Riyad Mahrez",
    "Achraf Hakimi",
    "Ilkay Gündogan",
    "Gini Wijnaldum",
    "Christian Pulisic",
    "James Rodríguez",
    "Dejan Kulusevski",
    "Dani Olmo",
    "João Félix",
    "Arturo Vidal",
    "Olivier Giroud",
    "Memphis Depay",
    "Milan Škriniar",
    "Mats Hummels",
    "Aymeric Laporte",
    "Roberto Firmino",
    "Hugo Lloris",
    "Jack Grealish",
    "Miralem Pjanić",
    "Keylor Navas",
    "Marcelo Brozović",
    "Donny van de Beek",
    "Lucas Hernández",
    "Raphael Varane",
    "Leroy Sané",
    "Dani Ceballos",
    "Aaron Ramsey",
    "Nicolo Barella",
    "Jordan Pickford",
    "John Stones",
    "Gerard Moreno",
    "Lucas Moura",
    "Koke",
    "Ferran Torres",
    "Mason Mount",
    "Eric García",
    "Rodrigo De Paul",
    "Youri Tielemans",
    "Ben Chilwell",
    "Jude Bellingham",
    "Federico Chiesa",
    "Pelé",
    "Diego Maradona",
    "Johan Cruyff",
    "Franz Beckenbauer",
    "Zinedine Zidane",
    "Ronaldo Nazário",
    "Michel Platini",
    "Ronaldinho",
    "George Best",
    "Bobby Charlton",
    "Marco van Basten",
    "Paolo Maldini",
    "Eusebio",
    "Alfredo Di Stéfano",
    "Ferenc Puskás",
    "Gerd Müller",
    "Roberto Baggio",
    "Eric Cantona",
    "Lothar Matthäus",
    "Thierry Henry"
  ];